/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function evenFibonacci(max) {
  let sum = 0;
  let back1 = 1;
  let back2 = 1;

  while (back1 + back2 < max) {
    let current = back1 + back2;
    back2 = back1;
    back1 = current;

    if (current % 2 === 0) {
      sum += current
    }
  }

  return sum;
}

evenFibonacci(4000000);